# Generated by Django 5.2.10 on 2026-02-12 22:25

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Телефон"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Почта")),
                ("full_name", models.CharField(help_text="Полное имя", max_length=300, verbose_name="Полное имя")),
                (
                    "first_name",
                    models.CharField(blank=True, help_text="Имя", max_length=300, null=True, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Фамилия", max_length=20, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "mid_name",
                    models.CharField(
                        blank=True, help_text="Отчество", max_length=20, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, help_text="День рождения", null=True, verbose_name="День рождения"),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="users/avatar/", verbose_name="Фото")),
                (
                    "communication",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("telegram", "telegram"),
                            ("WhatsApp", "WhatsApp"),
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                        ],
                        default="Phone",
                        max_length=9,
                        null=True,
                        verbose_name="Способ коммуникации",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Организация", max_length=30, null=True, verbose_name="Организация"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата изменения")),
                ("email_token", models.CharField(blank=True, max_length=100, null=True, verbose_name="email token")),
                ("phone_token", models.CharField(blank=True, max_length=100, null=True, verbose_name="phone token")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ["-updated_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Название темы переписки", max_length=300, verbose_name="Название"),
                ),
                ("message", models.TextField(help_text="Введите сообщение", verbose_name="Сообщение")),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Комментарии и примечания", null=True, verbose_name="Комментарии"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "новое"), ("read", "прочитано"), ("work", "в работе"), ("done", "закрыто")],
                        default="new",
                        help_text="Статус сообщения",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("deadline_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата ответа")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата изменения")),
                (
                    "communication",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("telegram", "telegram"),
                            ("WhatsApp", "WhatsApp"),
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                        ],
                        max_length=9,
                        null=True,
                        verbose_name="Способ коммуникации",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Имя клиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["updated_at"],
            },
        ),
    ]
