# Generated by Django 5.2.10 on 2026-02-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "новое"), ("read", "прочитано")],
                        default="new",
                        help_text="Статус сообщения",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "client_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_list",
                        to="users.clientmessage",
                        verbose_name="Список сообщений",
                    ),
                ),
            ],
        ),
    ]
