upstream django_app {
    server web:8000;
}

server {
    listen 80;

    # Укажите ваш IP из Yandex Cloud и домен
    server_name 158.160.14.153;

    include /etc/nginx/mime.types;

    # Максимальный размер загружаемых файлов (например, для медиа)
    client_max_body_size 100M;

    # Сжатие (Gzip) — крайне важно для тяжелых JS/CSS файлов Vite
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
    gzip_min_length 1000;

    # Раздача статики (путь должен совпадать с объемом в docker-compose)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d; # Добавляем кэширование для ускорения
        # Добавляем для предотвращения проблем с CORS при загрузке шрифтов
        add_header Access-Control-Allow-Origin *;
    }

    # Раздача медиа-файлов
    location /media/ {
        alias /app/media/;
    }

    # Проксирование запросов к Django
    location / {
        proxy_pass http://web:8000; # Используем созданный upstream

        # Передача необходимых заголовков для Django (CSRF, IP пользователя)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Важно для долгоиграющих запросов (например, загрузки данных)
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
    }
}