# Generated by Django 5.2.10 on 2026-02-12 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="event/preview/", verbose_name="Заставка"),
                ),
                (
                    "line_up",
                    models.CharField(
                        choices=[
                            ("SOLO", "соло"),
                            ("DUET", "дует"),
                            ("TRIO", "трио"),
                            ("QUARTET", "квартет"),
                            ("BAND", "группа"),
                            ("ORCHESTRA", "оркестр"),
                        ],
                        max_length=12,
                        verbose_name="Состав",
                    ),
                ),
                ("is_vocal", models.BooleanField(default=False, verbose_name="Вокал")),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="event/video/", verbose_name="Видео файл"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата проведения")),
                ("priority", models.PositiveIntegerField(default=0, verbose_name="Оценка приоритета")),
            ],
            options={
                "verbose_name": "мероприятие",
                "verbose_name_plural": "мероприятия",
                "ordering": ["-priority", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "инструмент",
                "verbose_name_plural": "инструменты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "ключевое слово",
                "verbose_name_plural": "ключевые слова",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="LineUp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(verbose_name="Название состава")),
                ("count", models.PositiveSmallIntegerField(verbose_name="Количество музыкантов")),
                ("is_vocal", models.BooleanField(verbose_name="Вокал")),
                ("image", models.ImageField(upload_to="event/image/", verbose_name="Фото")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("price", models.PositiveIntegerField(blank=True, null=True, verbose_name="Стоимость стандарт")),
                (
                    "price_premium",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Стоимость премиум"),
                ),
            ],
            options={
                "verbose_name": "состав",
                "verbose_name_plural": "составы",
                "ordering": ["count", "is_vocal"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.PositiveSmallIntegerField(verbose_name="Оценка приоритета")),
                ("image", models.ImageField(upload_to="event/image/", verbose_name="Фото")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.event", verbose_name="Мероприятие"
                    ),
                ),
            ],
            options={
                "verbose_name": "фото",
                "verbose_name_plural": "фото",
                "ordering": ["-event", "-priority"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="instruments",
            field=models.ManyToManyField(to="content.instrument", verbose_name="Инструменты"),
        ),
        migrations.AddField(
            model_name="event",
            name="keywords",
            field=models.ManyToManyField(to="content.keyword", verbose_name="Ключевые слова"),
        ),
        migrations.CreateModel(
            name="LineUpComposition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название состава инструментов")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("instruments", models.ManyToManyField(to="content.instrument", verbose_name="Инструменты")),
                (
                    "line_up",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.lineup", verbose_name="Состав"
                    ),
                ),
            ],
            options={
                "verbose_name": "состав инструментов",
                "verbose_name_plural": "составы инструментов",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.PositiveSmallIntegerField(verbose_name="Оценка приоритета")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="preview/video/", verbose_name="Заставка для видео"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(help_text="Например: https://vk.com", verbose_name="Ссылка на видео ВК"),
                ),
                (
                    "vk_hash",
                    models.CharField(
                        blank=True,
                        help_text="Если видео не грузится, скопируйте hash из кода экспорта",
                        max_length=100,
                        verbose_name="Хэш (необязательно)",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.event", verbose_name="Мероприятие"
                    ),
                ),
            ],
            options={
                "verbose_name": "видео",
                "verbose_name_plural": "видео",
                "ordering": ["-priority"],
            },
        ),
    ]
