# Generated by Django 5.2.10 on 2026-02-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="video_file",
        ),
        migrations.AddField(
            model_name="event",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_video_for_event",
                to="content.video",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="title",
            field=models.CharField(max_length=30, verbose_name="Название состава"),
        ),
        migrations.AlterField(
            model_name="video",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_videos",
                to="content.event",
                verbose_name="Мероприятие",
            ),
        ),
    ]
