# Generated by Django 5.2.10 on 2026-02-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_event_video_file_event_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineup",
            name="image",
            field=models.ImageField(upload_to="line_up/image/", verbose_name="Фото"),
        ),
    ]
