# Generated by Django 5.2.10 on 2026-02-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_lineup_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_photos",
                to="content.event",
                verbose_name="Мероприятие",
            ),
        ),
    ]
