# Generated by Django 5.2.10 on 2026-02-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_image_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineupcomposition",
            name="line_up",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_up_composition",
                to="content.lineup",
                verbose_name="Состав",
            ),
        ),
    ]
