# Generated by Django 5.2.10 on 2026-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_lineupcomposition_line_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="line_up",
            field=models.CharField(
                choices=[
                    ("Соло", "соло"),
                    ("Дуэт", "дует"),
                    ("Трио", "трио"),
                    ("Квартет", "квартет"),
                    ("Группа", "группа"),
                    ("Оркестр", "оркестр"),
                ],
                max_length=12,
                verbose_name="Состав",
            ),
        ),
    ]
