# Generated by Django 5.2.10 on 2026-02-26 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_event_line_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_photos",
                to="content.event",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_videos",
                to="content.event",
                verbose_name="Мероприятие",
            ),
        ),
    ]
