# Generated by Django 5.2.11 on 2026-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_image_event_alter_video_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_publicate",
            field=models.BooleanField(default=False, verbose_name="Публиковать"),
        ),
    ]
