# Generated by Django 5.2.10 on 2026-03-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_event_is_publicate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="content.event",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="content.event",
                verbose_name="Мероприятие",
            ),
        ),
    ]
