# Generated by Django 5.2.10 on 2026-03-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_image_event_alter_video_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["event", "priority"], "verbose_name": "фото", "verbose_name_plural": "фото"},
        ),
    ]
