# Generated by Django 5.2.10 on 2026-03-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_alter_image_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["priority", "-date"],
                "verbose_name": "мероприятие",
                "verbose_name_plural": "мероприятия",
            },
        ),
    ]
