# Generated by Django 5.2.10 on 2026-03-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_alter_event_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-priority", "-date"],
                "verbose_name": "мероприятие",
                "verbose_name_plural": "мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-event", "-priority"], "verbose_name": "фото", "verbose_name_plural": "фото"},
        ),
        migrations.AlterField(
            model_name="image",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name="Оценка приоритета"),
        ),
        migrations.AlterField(
            model_name="video",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name="Оценка приоритета"),
        ),
    ]
