# Generated by Django 5.2.10 on 2026-03-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_alter_event_options_alter_image_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-priority"], "verbose_name": "фото", "verbose_name_plural": "фото"},
        ),
    ]
