# Generated by Django 5.2.10 on 2026-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_alter_image_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_publicate",
            field=models.BooleanField(default=True, verbose_name="Публиковать"),
        ),
        migrations.AlterField(
            model_name="event",
            name="priority",
            field=models.PositiveIntegerField(default=1, verbose_name="Оценка приоритета"),
        ),
    ]
