# Generated by Django 5.2.10 on 2026-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_alter_event_is_publicate_alter_event_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineup",
            name="price_plus",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Стоимость стандарт+"),
        ),
    ]
